version: '3.9'

services:

  db:
    image: postgres

    volumes:
      - ./data/postgres:/var/lib/postgresql

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: superchat
      POSTGRES_DB: superchat

  redis:
    image: redis

    volumes:
      - ./data/redis:/usr/local/etc/redis

    ports:
      - 6379:6379
